# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Appeals Agent using Strands SDK.

Generates appeal letters for denied claims with deterministic validation,
deadline compliance checking, and structured letter assembly. Consults
payer rules via Gateway KB tools and saves final letters to S3.
"""

import json
import os
import time
import traceback
from dataclasses import asdict

import boto3
from bedrock_agentcore.runtime import BedrockAgentCoreApp
from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig
from bedrock_agentcore.memory.integrations.strands.session_manager import (
    AgentCoreMemorySessionManager,
)
from gateway.utils.gateway_access_token import get_gateway_access_token
from mcp.client.streamable_http import streamablehttp_client
from strands import Agent, tool
from strands.models import BedrockModel
from strands.tools.mcp import MCPClient

from appeal_letter_builder import (
    AppealLetterComponents,
    DenialInfo,
    PatientInfo,
    ProviderInfo,
    validate_and_build,
)
from deadline_tracker import check_filing_deadline

app = BedrockAgentCoreApp()

s3_client = boto3.client("s3")
APPEALS_BUCKET = os.environ.get("APPEALS_BUCKET", "")


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------


@tool
def check_appeal_deadline(payer_name: str, denial_date: str, appeal_level: str = "first_level") -> str:
    """Check filing deadline for an appeal and return urgency status.

    Must be called before generating an appeal letter to verify the filing
    window is still open.

    Args:
        payer_name: Insurance payer name (e.g. "Blue Cross Blue Shield", "UnitedHealthcare")
        denial_date: Date the denial was issued in YYYY-MM-DD format
        appeal_level: Appeal level — one of first_level, second_level, external_review, peer_to_peer

    Returns:
        JSON with deadline date, days remaining, and urgency classification
    """
    status = check_filing_deadline(payer_name, denial_date, appeal_level)
    return json.dumps(asdict(status), indent=2)


@tool
def validate_and_assemble_appeal(
    claim_id: str,
    denial_date: str,
    denial_reason_code: str,
    payer_name: str,
    patient_name: str,
    patient_dob: str,
    member_id: str,
    provider_name: str,
    provider_npi: str,
    date_of_service: str,
    clinical_rationale: str,
    requested_action: str,
    letter_body: str,
    remark_codes: str = "",
    authorization_number: str = "",
    provider_contact: str = "",
    supporting_documents: str = "",
    appeal_level: str = "First Level",
) -> str:
    """Validate appeal components and assemble a compliant HTML letter.

    Performs deterministic validation of all required fields, NPI format,
    CARC code validity, and clinical rationale completeness before assembling
    the letter. Returns validation errors if any required component is missing
    or malformed.

    Args:
        claim_id: Claim ID being appealed (e.g. CLM-JD-2026-001)
        denial_date: Denial date in YYYY-MM-DD format
        denial_reason_code: CARC denial reason code (e.g. "50", "197")
        payer_name: Insurance payer name
        patient_name: Patient full name
        patient_dob: Patient date of birth
        member_id: Patient member/subscriber ID
        provider_name: Treating provider name
        provider_npi: Provider NPI (10 digits)
        date_of_service: Date of service in YYYY-MM-DD format
        clinical_rationale: Detailed medical necessity justification
        requested_action: Specific remedy requested (e.g. "Approve prior authorization for MRI lumbar spine")
        letter_body: The appeal narrative body in HTML (generated by the LLM)
        remark_codes: Comma-separated RARC remark codes (optional)
        authorization_number: Prior auth number if applicable (optional)
        provider_contact: Provider contact info (optional)
        supporting_documents: Comma-separated list of enclosed documents (optional)
        appeal_level: Appeal level — First Level, Second Level, External Review (default: First Level)

    Returns:
        JSON with validation result. If valid, includes assembled HTML letter.
    """
    components = AppealLetterComponents(
        patient=PatientInfo(name=patient_name, date_of_birth=patient_dob, member_id=member_id),
        provider=ProviderInfo(name=provider_name, npi=provider_npi, contact=provider_contact),
        denial=DenialInfo(
            claim_id=claim_id,
            denial_date=denial_date,
            denial_reason_code=denial_reason_code,
            remark_codes=[c.strip() for c in remark_codes.split(",") if c.strip()],
            payer_name=payer_name,
            authorization_number=authorization_number,
        ),
        date_of_service=date_of_service,
        clinical_rationale=clinical_rationale,
        supporting_documents=[d.strip() for d in supporting_documents.split(",") if d.strip()],
        requested_action=requested_action,
        appeal_level=appeal_level,
    )

    result = validate_and_build(components, letter_body)
    # Don't serialize the full HTML back to the LLM — just status + issues
    response = {"valid": result["valid"], "issues": result["issues"]}
    if result["html"]:
        response["html_length"] = len(result["html"])
        response["_html"] = result["html"]  # kept for save step
    return json.dumps(response, indent=2)


@tool
def save_appeal_letter(claim_id: str, letter_html: str) -> dict:
    """Save a validated appeal letter to S3 and return a presigned download URL.

    Only call this after validate_and_assemble_appeal returns valid=true.

    Args:
        claim_id: The claim ID this appeal is for (e.g. CLM-JD-2026-001)
        letter_html: The complete appeal letter HTML from validate_and_assemble_appeal

    Returns:
        dict with s3Key and downloadUrl
    """
    if not APPEALS_BUCKET:
        return {"error": "APPEALS_BUCKET not configured", "s3Key": None, "downloadUrl": None}

    ts = int(time.time())
    s3_key = f"appeals/{claim_id}/{ts}-appeal.html"

    s3_client.put_object(
        Bucket=APPEALS_BUCKET,
        Key=s3_key,
        Body=letter_html.encode("utf-8"),
        ContentType="text/html",
    )

    url = s3_client.generate_presigned_url(
        "get_object",
        Params={"Bucket": APPEALS_BUCKET, "Key": s3_key},
        ExpiresIn=3600,
    )

    return {"s3Key": s3_key, "downloadUrl": url, "claimId": claim_id}


# ---------------------------------------------------------------------------
# Agent setup
# ---------------------------------------------------------------------------


def get_system_prompt(ssm_path: str) -> str:
    """Fetch system prompt from Bedrock Prompt Management via SSM."""
    region = os.environ.get("AWS_REGION", os.environ.get("AWS_DEFAULT_REGION", "us-east-1"))
    ssm = boto3.client("ssm", region_name=region)
    prompt_arn = ssm.get_parameter(Name=ssm_path)["Parameter"]["Value"]

    bedrock = boto3.client("bedrock-agent", region_name=region)
    parts = prompt_arn.split(":")
    prompt_id = parts[-2].split("/")[-1]
    prompt_version = parts[-1]
    resp = bedrock.get_prompt(promptIdentifier=prompt_id, promptVersion=prompt_version)
    return resp["variants"][0]["templateConfiguration"]["text"]["text"]


def get_ssm_parameter(name: str) -> str:
    region = os.environ.get("AWS_REGION", os.environ.get("AWS_DEFAULT_REGION", "us-east-1"))
    ssm = boto3.client("ssm", region_name=region)
    return ssm.get_parameter(Name=name)["Parameter"]["Value"]


def create_gateway_mcp_client(access_token: str) -> MCPClient:
    stack_name = os.environ.get("STACK_NAME")
    if not stack_name:
        raise ValueError("STACK_NAME environment variable is required")

    gateway_url = get_ssm_parameter(f"/{stack_name}/gateway_url")

    return MCPClient(
        lambda: streamablehttp_client(
            url=gateway_url, headers={"Authorization": f"Bearer {access_token}"}
        ),
        prefix="gateway",
    )


def create_appeals_agent(user_id: str, session_id: str) -> Agent:
    prompt_ssm_path = os.environ.get("SYSTEM_PROMPT_SSM_PATH")
    if not prompt_ssm_path:
        raise ValueError("SYSTEM_PROMPT_SSM_PATH environment variable is required")

    system_prompt = get_system_prompt(prompt_ssm_path)

    model = BedrockModel(
        model_id="us.anthropic.claude-sonnet-4-5-20250929-v1:0",
        temperature=0.1,
    )

    memory_id = os.environ.get("MEMORY_ID")
    if not memory_id:
        raise ValueError("MEMORY_ID environment variable is required")

    session_manager = AgentCoreMemorySessionManager(
        agentcore_memory_config=AgentCoreMemoryConfig(
            memory_id=memory_id, session_id=session_id, actor_id=user_id
        ),
        region_name=os.environ.get("AWS_DEFAULT_REGION", "us-east-1"),
    )

    access_token = get_gateway_access_token()
    gateway_client = create_gateway_mcp_client(access_token)

    return Agent(
        name="AppealsAgent",
        system_prompt=system_prompt,
        tools=[
            gateway_client,
            check_appeal_deadline,
            validate_and_assemble_appeal,
            save_appeal_letter,
        ],
        model=model,
        session_manager=session_manager,
        trace_attributes={"user.id": user_id, "session.id": session_id},
    )


@app.entrypoint
async def agent_stream(payload):
    user_query = payload.get("prompt")
    user_id = payload.get("userId")
    session_id = payload.get("runtimeSessionId")

    if not all([user_query, user_id, session_id]):
        yield {"status": "error", "error": "Missing required fields: prompt, userId, or runtimeSessionId"}
        return

    try:
        agent = create_appeals_agent(user_id, session_id)
        async for event in agent.stream_async(user_query):
            yield event
    except Exception as e:
        traceback.print_exc()
        yield {"status": "error", "error": str(e)}


if __name__ == "__main__":
    app.run()
